# 本文集用于存储配置参数


################## 多目标遗传算法配置参数 ##################
NSGA_config:
  # 群体大小：20~100
  population_size: 20
  # 遗传算法的终止进化代数：100~500
  termination_condition: 250
  # 交叉概率：0.4~0.99
  crossover_probability: 0.5
  # 变异概率：0.0001~0.1
  mutation_probability: 0.01

################## 系统配置参数 ##################
# 迭代结果保存频率

# 是否输出图片
